pub enum CustomEvent {
    SwitchTo(usize),
    ToggleLayout(),
    StartDock(),
    OpenPanel(),
    OpenHomePanel(),
    ClosePanel(),
    HomePanelLoadDaily(),
    HomePanelLoadWeather(),
    GoogleOauthLogin(String),
    OpenAppsPanel(),
    AppsPanelLoadApps(),
}
// AppsPanelSearch(String),
// NetworkPanelLoadWiFi(),
// NetworkPanelShareWiFi(),
// OpenNetworkPanel(),
// NetworkPanelConnectWiFi(String, String),
